[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.146.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.146.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.146.0"
